name: Check

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - run: |
          git -c url.https://github.com/.insteadOf=git@github.com: submodule update --init --depth 1 konfik liminal
          git -c url.https://github.com/.insteadOf=git@github.com: -C liminal submodule update --init --depth 1 konfik
      - uses: crosshatch/konfik/.github/actions/configure_environment@main
      - run: pnpm oxfmt --check
      - run: pnpm build
      - run: pnpm test
        env:
          CDP_API_KEY_ID: ${{ vars.CDP_API_KEY_ID }}
          CDP_API_KEY_SECRET: ${{ secrets.CDP_API_KEY_SECRET }}
          EVM_SEED_PHRASE: ${{ secrets.EVM_SEED_PHRASE }}
          PAY_TO_EVM: ${{ vars.PAY_TO_EVM }}
